[build]
    publish = "public/"
    command = "yarn predocs:dev && yarn docs:build"
[[redirects]]
  from = "/sdk/dotnet/*"
  to = "https://silly-aryabhata-ec1db8.netlify.com/:splat"
  status = 200
  force = true
