name: Lint
on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Vale
        uses: errata-ai/vale-action@v1.0.4
        with:
          styles: |
            https://github.com/EventStore/Style-Guide/releases/download/0.1/EventStore.zip
          config: https://raw.githubusercontent.com/EventStore/Style-Guide/master/.vale.ini?token=AAAKIYFECFCPHNCQUUP5BK26SVXVO
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
